### ISSUE TITLE
Natively generate two big prime numbers

### ISSUE THREAD

**Issue by alanyee** [alanyee/rsa-keygen#10]
Currently, the CLI requires the user to supply in their own prime numbers however they generate them:
```
  -p prime prime, --primes prime prime
                        Load from two big prime numbers
```
Having the CLI generate them natively would be nice.

**Comment by LyndonFan** [comment]
Hi, is the issue available? I can work on it!

**Comment by alanyee** [comment]
Yes, this issue is still available. Go for it!
