### ISSUE TITLE
Add GitHub template for GitHub issues

### ISSUE THREAD

**Issue by alanyee** [alanyee/rsa-keygen#9]

**Comment by tharun634** [comment]
Hello @alanyee , I would like to take this up

**Comment by alanyee** [comment]
Sounds good to me

**Comment by tharun634** [comment]
Are you looking for any specific sections? Fields to includes as such? or a simple one would do?

**Comment by alanyee** [comment]
Something like https://github.com/alanyee/rsa-keygen/pull/11 is fine. A `description` section at the very least, but up to you for which sections you think are important.

**Comment by alanyee** [comment]
Thank you! 💯
